// <auto-generated />
using System;
using EconomyBackPortifolio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EconomyBackPortifolio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EconomyBackPortifolio.Models.Users", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnName("name").HasColumnType("character varying(100)");
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnName("email").HasColumnType("character varying(150)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(255).HasColumnName("password_hash").HasColumnType("character varying(255)");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("Id").HasName("pk_users");
                b.HasIndex("Email").IsUnique().HasDatabaseName("uk_users_email");
                b.ToTable("users");
            });

            modelBuilder.Entity("EconomyBackPortifolio.Models.Assets", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<string>("Symbol").IsRequired().HasMaxLength(20).HasColumnName("symbol").HasColumnType("character varying(20)");
                b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnName("name").HasColumnType("character varying(150)");
                b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnName("type").HasColumnType("character varying(20)");
                b.Property<string>("Currency").IsRequired().HasMaxLength(10).HasColumnName("currency").HasColumnType("character varying(10)");
                b.Property<decimal>("CurrentPrice").HasPrecision(18, 6).HasColumnName("current_price").HasColumnType("numeric(18,6)");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("Id").HasName("pk_assets");
                b.HasIndex("Symbol").IsUnique().HasDatabaseName("uk_assets_symbol");
                b.ToTable("assets");
            });

            modelBuilder.Entity("EconomyBackPortifolio.Models.Wallets", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnName("user_id").HasColumnType("uuid");
                b.Property<string>("Currency").IsRequired().HasMaxLength(10).HasColumnName("currency").HasColumnType("character varying(10)");
                b.Property<decimal>("Balance").HasPrecision(18, 2).HasColumnName("balance").HasColumnType("numeric(18,2)");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("Id").HasName("pk_wallets");
                b.HasIndex("UserId").HasDatabaseName("ix_wallets_user_id");
                b.ToTable("wallets");
                b.HasOne("EconomyBackPortifolio.Models.Users", "User").WithMany().HasForeignKey("UserId").HasConstraintName("fk_wallets_user_id__users").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("EconomyBackPortifolio.Models.Positions", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<Guid>("WalletId").HasColumnName("wallet_id").HasColumnType("uuid");
                b.Property<Guid>("AssetId").HasColumnName("asset_id").HasColumnType("uuid");
                b.Property<decimal>("Quantity").HasPrecision(18, 6).HasColumnName("quantity").HasColumnType("numeric(18,6)");
                b.Property<decimal>("AveragePrice").HasPrecision(18, 6).HasColumnName("average_price").HasColumnType("numeric(18,6)");
                b.Property<decimal>("TotalInvested").HasPrecision(18, 2).HasColumnName("total_invested").HasColumnType("numeric(18,2)");
                b.Property<DateTime>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
                b.HasKey("Id").HasName("pk_positions");
                b.HasIndex(new[] { "WalletId", "AssetId" }).IsUnique().HasDatabaseName("uk_positions_wallet_asset");
                b.ToTable("positions");
                b.HasOne("EconomyBackPortifolio.Models.Wallets", "Wallet").WithMany().HasForeignKey("WalletId").HasConstraintName("fk_positions_wallet_id__wallets").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("EconomyBackPortifolio.Models.Assets", "Asset").WithMany().HasForeignKey("AssetId").HasConstraintName("fk_positions_asset_id__assets").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("EconomyBackPortifolio.Models.Transactions", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<Guid>("WalletId").HasColumnName("wallet_id").HasColumnType("uuid");
                b.Property<Guid?>("AssetId").HasColumnName("asset_id").HasColumnType("uuid");
                b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnName("type").HasColumnType("character varying(20)");
                b.Property<decimal?>("Quantity").HasPrecision(18, 6).HasColumnName("quantity").HasColumnType("numeric(18,6)");
                b.Property<decimal?>("Price").HasPrecision(18, 6).HasColumnName("price").HasColumnType("numeric(18,6)");
                b.Property<decimal>("Total").HasPrecision(18, 2).HasColumnName("total").HasColumnType("numeric(18,2)");
                b.Property<DateTime>("TransactionAt").HasColumnName("transaction_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("Id").HasName("pk_transactions");
                b.HasIndex("WalletId").HasDatabaseName("ix_transactions_wallet_id");
                b.HasIndex("AssetId").HasDatabaseName("ix_transactions_asset_id");
                b.ToTable("transactions");
                b.HasOne("EconomyBackPortifolio.Models.Wallets", "Wallet").WithMany().HasForeignKey("WalletId").HasConstraintName("fk_transactions_wallet_id__wallets").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("EconomyBackPortifolio.Models.Assets", "Asset").WithMany().HasForeignKey("AssetId").HasConstraintName("fk_transactions_asset_id__assets").OnDelete(DeleteBehavior.SetNull);
            });
#pragma warning restore 612, 618
        }
    }
}
